apiVersion: v1
kind: Service
metadata:
  name: serverservice
  labels:
    name: serverservice
    app: server
spec:
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  type: LoadBalancer
  selector:
     app: server
