apiVersion: v1
kind: Pod
metadata:
  name: requestpod
  labels:
    name: requestpod
    app: talk
spec:
  containers:
  - name: requestpod
    image: awinash21/request:latest
    ports:
         - containerPort: 8000
           name: http
           protocol: TCP
           
