apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serverpod-v2
  labels:
    app: server
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        version: v2
    spec:
      containers:
      - name: serverpod
        image: awinash21/server1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
